spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/board?useUnicode=true&serverTimezone=Asia/Seoul
    username: newuser
    password: a1234
#  live reloading ? ?? ?? ??
devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
  thymeleaf:
    cache: false

